version: '3.8'

services:
  server_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_mariadb_demo
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=test_db
      - MARIADB_ROOT_PASSWORD=123456
